/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceAlterarPedido;

import interfacesSistema.Datastore;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextPane;
import projetofinalpizzaria.*;


/**
 *
 * @author lelim
 */
public class BuscarClienteCadastrado extends javax.swing.JPanel {
    Datastore datastore = Datastore.getInstance();
    private boolean pedidoAberto = false;
    private int indexCliente;
    /**
     * Creates new form BuscarClienteCadastrado
     */
    public BuscarClienteCadastrado() {
        initComponents();
        botaoAction.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTelefone = new javax.swing.JTextPane();
        btnBuscarCliente = new javax.swing.JButton();
        lblMensagemValidacao = new javax.swing.JLabel();
        lblMensagemAlteracao = new javax.swing.JLabel();
        botaoAction = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Buscar cliente cadastrado por telefone");

        lblTelefone.setText("Telefone:");

        jScrollPane1.setViewportView(txtTelefone);

        btnBuscarCliente.setBackground(new java.awt.Color(0, 153, 153));
        btnBuscarCliente.setText("Buscar Cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        lblMensagemValidacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMensagemValidacao.setForeground(new java.awt.Color(0, 153, 153));

        lblMensagemAlteracao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMensagemAlteracao.setForeground(new java.awt.Color(0, 153, 153));

        botaoAction.setBackground(new java.awt.Color(0, 153, 153));
        botaoAction.setText("Mostrar Pedidos em Aberto");
        botaoAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensagemValidacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnBuscarCliente)))
                        .addGap(0, 162, Short.MAX_VALUE))
                    .addComponent(lblMensagemAlteracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(botaoAction)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone)
                    .addComponent(btnBuscarCliente))
                .addGap(18, 18, 18)
                .addComponent(lblMensagemValidacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensagemAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(botaoAction)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        indexCliente = datastore.buscarPorTelefone(getTxtTelefone().getText());
        if (indexCliente >= 0) {
            getLblMensagemValidacao().setText("Cliente cadastrado!");
            boolean pedido = datastore.getClientes().get(indexCliente).temPedidoAberto();
            botaoAction.setVisible(true);
            if (pedido == true) {
                pedidoAberto = true;
                lblMensagemAlteracao.setText("O cliente possui pedidos em aberto para alteração!");
                botaoAction.setText("Alterar pedido");
            } else {
                pedidoAberto = false;
                lblMensagemAlteracao.setText("O cliente não possui pedidos em aberto para alteração!");
                botaoAction.setText("Abrir pedido");
            }
        } else {
            botaoAction.setVisible(false);
            getLblMensagemValidacao().setText("Cliente não cadastrado! Favor realizar o cadastro antes de prosseguir.");
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void botaoActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionActionPerformed
        //this.setVisible(false);
        Carrinho carrinho;
        ArrayList<Forma> pizza;
        if (pedidoAberto){
            pizza = datastore.getClientes().get(indexCliente).getPedidoAberto().getPizzas();
        }
        else{
            pizza = new ArrayList();
            Pedido pedido = new Pedido(datastore.getClientes().get(indexCliente).getPedidos().size());
            datastore.getClientes().get(indexCliente).getPedidos().add(pedido);
        }
        carrinho = new Carrinho(indexCliente);
        carrinho.setVisible(true);
        carrinho.setResizable(false);
        //System.out.println("funciona");
    }//GEN-LAST:event_botaoActionActionPerformed

    public JButton getBtnBuscarCliente() {
        return btnBuscarCliente;
    }

    public JLabel getLblMensagemValidacao() {
        return lblMensagemValidacao;
    }

    public void setLblMensagemValidacao(JLabel lblMensagemValidacao) {
        this.lblMensagemValidacao = lblMensagemValidacao;
    }

    public JTextPane getTxtTelefone() {
        return txtTelefone;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAction;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensagemAlteracao;
    private javax.swing.JLabel lblMensagemValidacao;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextPane txtTelefone;
    // End of variables declaration//GEN-END:variables
}
