/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CadastroSabores;

import interfacesSistema.*;
import javax.swing.JButton;

/**
 *
 * @author lelim
 */
public class botoesSabores extends javax.swing.JPanel {
    private TelaSabores janela;
    private TabelaSabores tabela;
   
    /**
     * Creates new form botoesCadastro
     */
    public botoesSabores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrarSabor = new javax.swing.JButton();
        btnAtualizarSabor = new javax.swing.JButton();
        btnExcluirSabor = new javax.swing.JButton();

        btnCadastrarSabor.setBackground(new java.awt.Color(0, 153, 153));
        btnCadastrarSabor.setText("Cadastrar Sabor");
        btnCadastrarSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarSaborActionPerformed(evt);
            }
        });

        btnAtualizarSabor.setBackground(new java.awt.Color(0, 153, 153));
        btnAtualizarSabor.setText("Atualizar Sabor");
        btnAtualizarSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarSaborActionPerformed(evt);
            }
        });

        btnExcluirSabor.setBackground(new java.awt.Color(0, 153, 153));
        btnExcluirSabor.setText("Excluir Sabor");
        btnExcluirSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirSaborActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastrarSabor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnAtualizarSabor)
                .addGap(29, 29, 29)
                .addComponent(btnExcluirSabor)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarSabor)
                    .addComponent(btnExcluirSabor)
                    .addComponent(btnAtualizarSabor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarSaborActionPerformed
        janela.cadastrar();
    }//GEN-LAST:event_btnCadastrarSaborActionPerformed

    private void btnAtualizarSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarSaborActionPerformed
        janela.alterar();
    }//GEN-LAST:event_btnAtualizarSaborActionPerformed

    private void btnExcluirSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirSaborActionPerformed
        janela.excluir();
    }//GEN-LAST:event_btnExcluirSaborActionPerformed

    public void setJanela(TelaSabores janela) {
        this.janela = janela;
    }

    public JButton getBtnCadastrarCliente() {
        return btnCadastrarSabor;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarSabor;
    private javax.swing.JButton btnCadastrarSabor;
    private javax.swing.JButton btnExcluirSabor;
    // End of variables declaration//GEN-END:variables
}
