/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CadastroSabores;

import interfacesSistema.*;
import javax.swing.JTextPane;

/**
 *
 * @author lelim
 */
public class inputSabores extends javax.swing.JPanel {
    
    private int tipo = -1;
    /**
     * Creates new form formularioCliente
     */
    public inputSabores() {
        initComponents();
    }
    
    public int getTipo(){
        return this.tipo;
    }
    
    public String getNomeSabor(){
       return this.btnTextName.getText();
    }
    
    public long getID(){
        try{
            return Long.parseLong(this.btnTextID.getText());
        } catch (Exception e){
            return -1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnSimples = new javax.swing.JRadioButton();
        btnEspecial = new javax.swing.JRadioButton();
        btnPremium = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTextName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnTextID = new javax.swing.JTextField();

        buttonGroup1.add(btnSimples);
        btnSimples.setText("Simples");
        btnSimples.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimplesMouseClicked(evt);
            }
        });

        buttonGroup1.add(btnEspecial);
        btnEspecial.setText("Especial");
        btnEspecial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEspecialMouseClicked(evt);
            }
        });

        buttonGroup1.add(btnPremium);
        btnPremium.setText("Premium");
        btnPremium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPremiumMouseClicked(evt);
            }
        });

        jLabel1.setText("Tipo de sabor:");

        jLabel2.setText("Sabor");

        jLabel3.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTextID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimples)
                        .addGap(18, 18, 18)
                        .addComponent(btnEspecial)
                        .addGap(18, 18, 18)
                        .addComponent(btnPremium))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimples)
                    .addComponent(btnEspecial)
                    .addComponent(btnPremium)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimplesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimplesMouseClicked
        this.tipo = 0;
    }//GEN-LAST:event_btnSimplesMouseClicked

    private void btnEspecialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEspecialMouseClicked
        this.tipo = 1;
    }//GEN-LAST:event_btnEspecialMouseClicked

    private void btnPremiumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPremiumMouseClicked
        this.tipo = 2;
    }//GEN-LAST:event_btnPremiumMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnEspecial;
    private javax.swing.JRadioButton btnPremium;
    private javax.swing.JRadioButton btnSimples;
    private javax.swing.JTextField btnTextID;
    private javax.swing.JTextField btnTextName;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
