/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesSistema;

import java.util.ArrayList;
import projetofinalpizzaria.Cliente;

/**
 *
 * @author lelim
 */
public class JanelaCadastroCliente extends javax.swing.JFrame {
    private long clienteID;
    /**
     * Creates new form JanelaCadastroCliente
     */
    public JanelaCadastroCliente() {
        initComponents();
        botoesCadastro1.setJanela(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelaClientesCadastrados1 = new interfacesSistema.TabelaClientesCadastrados();
        botoesCadastro1 = new interfacesSistema.botoesCadastro();
        formularioCliente1 = new interfacesSistema.formularioCliente();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tabelaClientesCadastrados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botoesCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(formularioCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(formularioCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botoesCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaClientesCadastrados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ArrayList<Cliente> clientes = new ArrayList<>();
    Cliente cliente;
    public void cadastrarCliente() {
        String nome = formularioCliente1.getTxtNome().getText();
        String sobrenome = formularioCliente1.getTxtSobrenome().getText();
        String telefone = formularioCliente1.getTxtTelefone().getText();
        
        cliente = new Cliente(clienteID++, nome, sobrenome, telefone);
        clientes.add(cliente);
        tabelaClientesCadastrados1.getModeloTabela().adicionaContato(cliente);
    }
    
    public void excluirCadastro() {
        int idCliente = Integer.parseInt(formularioCliente1.getTxtID().getText());
        tabelaClientesCadastrados1.getModeloTabela().removeContato(clientes.get(idCliente));
        clientes.remove(clientes.get(idCliente));
        clienteID--;
        
        for (int i = 0; i < clientes.size(); i++) {
            if (idCliente < clientes.get(i).getId()) {
                clientes.get(i).setId(clientes.get(i).getId() - 1);
            }
        }
    }
    
    public void alterarCadastro() {
        String nome = formularioCliente1.getTxtNome().getText();
        String sobrenome = formularioCliente1.getTxtSobrenome().getText();
        String telefone = formularioCliente1.getTxtTelefone().getText();
        int ID = Integer.parseInt(formularioCliente1.getTxtID().getText());
        tabelaClientesCadastrados1.getModeloTabela().setValueAt(nome, ID, 1);
        tabelaClientesCadastrados1.getModeloTabela().setValueAt(sobrenome, ID, 2);
        tabelaClientesCadastrados1.getModeloTabela().setValueAt(telefone, ID, 3);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private interfacesSistema.botoesCadastro botoesCadastro1;
    private interfacesSistema.formularioCliente formularioCliente1;
    private interfacesSistema.TabelaClientesCadastrados tabelaClientesCadastrados1;
    // End of variables declaration//GEN-END:variables
}
